# Generated by Django 2.2.15 on 2020-09-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minecraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.TextField()),
                ('server_version', models.TextField()),
                ('server_ip', models.TextField()),
                ('server_png', models.ImageField(upload_to='')),
                ('server_time', models.DurationField()),
            ],
        ),
    ]
