# Generated by Django 2.2.15 on 2020-09-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameServers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minecraft',
            name='server_png',
            field=models.TextField(),
        ),
    ]
